name: Update Readme

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 5 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - uses: actions/cache@v1
        name: Cache dependencies and build outputs to improve workflow execution time.
        with:
          path: node_modules
          key: ${{ runner.os }}-js-${{ hashFiles('package-lock.json') }}

      - run: npm install
        name: Install dependencies

      - run: node getSolutions.js
        name: Generate README file

      - run: |-
          git add .
          git diff
          git config --global user.email "github-action-bot@example.com"
          git config --global user.name "GitHub Action Bot"
          git commit -m "Updated README" -a || echo "No changes to commit"
          git push
        name: Commit and Push new README.md to the repository
